/**
 * Copyright (C) 2026 TG11
 *
 * Kernel built-in symbol table lookup.
 *
 * A flat sorted table of {address, name_offset} pairs is embedded in the
 * kernel binary at build time (generated by tools/gen_kernel_syms.sh from
 * the kernel ELF via nm).  ksym_lookup() performs a binary search over this
 * table to map any kernel code address back to a function name.
 */
#ifndef TG11_KSYM_H
#define TG11_KSYM_H

typedef struct {
    unsigned long addr;
    unsigned long name_off;   /* byte offset into ksym_names string table */
} ksym_entry_t;

/**
 * Look up a kernel symbol by address.
 *
 * Returns the name of the nearest symbol whose address is <= addr, or NULL
 * if no such symbol exists in the table.
 *
 * If out_offset is non-NULL, *out_offset is set to (addr - symbol_base).
 */
const char *ksym_lookup(unsigned long addr, unsigned long *out_offset);

#endif /* TG11_KSYM_H */
