#!/bin/sh
# tools/gen_kernel_syms.sh
#
# Generate a C source file containing the kernel symbol table.
# The output is compiled and linked into the final kernel binary so that
# ksym_lookup() can resolve function addresses to names at runtime.
#
# Usage: gen_kernel_syms.sh <nm-binary> <kernel.elf>
#
# The generated file defines:
#   const char         *ksym_names        -- null-terminated name string table
#   const ksym_entry_t *ksym_table        -- sorted {addr, name_off} array
#   const unsigned long ksym_table_count  -- number of entries
#
# Only T/t (text/function) symbols with non-dot names are included, since
# those are the symbols useful for backtrace resolution.

NM="$1"
ELF="$2"

if [ -z "$NM" ] || [ -z "$ELF" ]; then
    echo "Usage: $0 <nm-binary> <kernel.elf>" >&2
    exit 1
fi

"$NM" --numeric-sort --defined-only "$ELF" | awk '
BEGIN { n = 0 }
/^[0-9a-f]+ [Tt] [^.]/ {
    addr = $1
    name = $3
    if (length(name) == 0 || length(addr) == 0) next
    addrs[n] = addr
    names[n] = name
    n++
}
END {
    print "/* Auto-generated by tools/gen_kernel_syms.sh -- do not edit */"
    print "#include \"ksym.h\""
    print ""
    print "static const char ksym_names_buf[] ="
    off = 0
    for (i = 0; i < n; i++) {
        printf "    \"%s\\0\"\n", names[i]
        offsets[i] = off
        off += length(names[i]) + 1
    }
    print ";"
    print ""
    print "static const ksym_entry_t ksym_table_buf[] = {"
    for (i = 0; i < n; i++) {
        printf "    { 0x%sUL, %dUL },\n", addrs[i], offsets[i]
    }
    print "};"
    print ""
    print "const char         *ksym_names       = ksym_names_buf;"
    print "const ksym_entry_t *ksym_table       = ksym_table_buf;"
    printf "const unsigned long ksym_table_count = %dUL;\n", n
}'
